Repository f-lab-edu/somoim-clone, pull requests merged in 2022-06, with the labels that each got.

#37 회원가입 기능 구현
  build.gradle
  src/main/java/com/somoim/SomoimApplication.java
  src/main/java/com/somoim/config/DatabaseConfig.java
  src/main/java/com/somoim/config/WebSecurityConfig.java
  src/main/java/com/somoim/controller/UserController.java
  src/main/java/com/somoim/exception/DuplicateEmailException.java
  src/main/java/com/somoim/mapper/UserMapper.java
  src/main/java/com/somoim/model/dao/User.java
  src/main/java/com/somoim/model/dto/SignUpUser.java
  src/main/java/com/somoim/service/UserService.java
  src/main/resources/application-local.yml
  src/main/resources/mapper/UserMapper.xml
  src/test/java/com/somoim/service/UserServiceTest.java
Labels: feture

#38 seed data 추가
  src/main/resources/application-local.yml
  src/main/resources/seeds/data.sql
  src/main/resources/seeds/schema.sql
Labels: feture

#44 multi datasource 적용하여 readonly일 때, secondary db를 조회하도록 처리
  src/main/java/com/somoim/config/DataSourceConfig.java
  src/main/java/com/somoim/config/DatabaseConfig.java
  src/main/java/com/somoim/enumeration/DataSourceType.java
  src/main/resources/application-local.yml
Labels: feture

#46 - 회원가입 시 modify_at 정보도 추가되도록 수정
  src/main/java/com/somoim/model/dao/User.java
  src/main/java/com/somoim/service/UserService.java
  src/main/resources/mapper/UserMapper.xml
  src/test/java/com/somoim/service/UserServiceTest.java
Labels: enhancement

#47 4 로그인로그아웃 구현
  build.gradle
  src/main/java/com/somoim/config/DatabaseConfig.java
  src/main/java/com/somoim/config/RedisConfig.java
  src/main/java/com/somoim/controller/UserController.java
  src/main/java/com/somoim/mapper/UserMapper.java
  src/main/java/com/somoim/model/dao/User.java
  src/main/java/com/somoim/model/dto/LoginUser.java
  src/main/java/com/somoim/service/UserService.java
  src/main/resources/application-local.yml
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/mybatis-config.xml
  src/test/java/com/somoim/service/UserServiceTest.java
Labels: feature

#50 5 프로필 정보 조회변경
  src/main/java/com/somoim/controller/ProfileController.java
  src/main/java/com/somoim/enumeration/GenderType.java
  src/main/java/com/somoim/exception/NotFoundException.java
  src/main/java/com/somoim/mapper/ProfileMapper.java
  src/main/java/com/somoim/model/dao/User.java
  src/main/java/com/somoim/model/dto/UserProfile.java
  src/main/java/com/somoim/service/ProfileService.java
  src/main/java/com/somoim/service/UserService.java
  src/main/resources/mapper/ProfileMapper.xml
  src/test/java/com/somoim/service/ProfileServiceTest.java
  src/test/java/com/somoim/service/UserServiceTest.java
Labels: feature

#54 사용자 관심사 변경 구현입니다
  src/main/java/com/somoim/controller/InterestController.java
  src/main/java/com/somoim/mapper/InterestMapper.java
  src/main/java/com/somoim/model/dao/Interest.java
  src/main/java/com/somoim/model/dto/UpdateInterest.java
  src/main/java/com/somoim/model/dto/UserInterest.java
  src/main/java/com/somoim/service/InterestService.java
  src/main/resources/mapper/InterestMapper.xml
  src/test/java/com/somoim/service/InterestServiceTest.java
Labels: feature
